# Created by Jekyll Writer
title: Welcome
author: GN
description: Blog
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: jekyllwriter
github_username: jekyllwriter
gems:
  - jekyll-paginate
markdown: kramdown
baseurl: ''

theme: jekyll-theme-cayman
